{% set version = "0.2.1" %}

package:
  name: stim
  version: {{ version }}

source:
  url: https://github.com/PreibischLab/STIM/archive/refs/tags/v{{ version }}.zip
  sha256: 49ea61a664228073049c7b6bd1b69a5836091872bded2bfea5863aeaa188e445

build:
  number: 0

requirements:
  build:
    - openjdk
    - maven
  host:
    - openjdk
  run:
    - openjdk
    - blosc

test:
  commands:
    - st-help --version

about:
  home: https://github.com/PreibischLab/STIM
  summary: 'STIM - the Spatial Transcriptomics ImgLib2/Imaging Project'
  description: |
    STIM is a framework for managing, storage, viewing, and processing spatial
    transcriptomics data, which builds on the powerful libraries Imglib2, N5,
    BigDataViewer and Fiji.
  license: GPL-3.0-or-later
  license_file: license

extra:
  recipe-maintainers:
    - minnerbe
    - StephanPreibisch
