{% set version = "0.4.0" %}

package:
  name: stim
  version: {{ version }}

source:
  url: https://github.com/PreibischLab/STIM/archive/refs/tags/v{{ version }}.zip
  sha256: 76dc65336244ffa989c393891487dae95049a18e872b784fba0a432957c6951d

build:
  number: 0

requirements:
  build:
    - openjdk
    - blosc
    - maven
  host:
    - openjdk
  run:
    - openjdk
    - blosc

test:
  commands:
    - st-help --version

about:
  home: https://github.com/PreibischLab/STIM
  summary: 'STIM - the Spatial Transcriptomics ImgLib2/Imaging Project'
  description: |
    STIM is a framework for managing, storage, viewing, and processing spatial
    transcriptomics data, which builds on the powerful libraries Imglib2, N5,
    BigDataViewer and Fiji.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - minnerbe
    - StephanPreibisch
